const {test,before,beforeEach,after}=require('node:test');
const assert=require('node:assert/strict');
const {allocateMinutes,weekBounds,calendarDate}=require('../src/modules/capacity/calculation');
test('capacity distributes a full estimate across calendar dates in the selected UTC week',()=>{assert.deepEqual(weekBounds('2026-09-23'),{from:'2026-09-21',to:'2026-09-27'});assert.equal(allocateMinutes('14','2026-09-21','2026-10-04','2026-09-21').minutes,420);assert.equal(allocateMinutes('14','2026-09-21','2026-10-04','2026-10-12').minutes,0);});
test('missing estimates and schedules remain explicit, including valid zero estimates',()=>{assert.equal(allocateMinutes(null,'2026-09-21','2026-09-22','2026-09-21').unestimated,true);assert.equal(allocateMinutes('0','2026-09-21','2026-09-22','2026-09-21').unestimated,false);assert.equal(allocateMinutes('8',null,null,'2026-09-21').unscheduled,true);assert.equal(calendarDate.safeParse('2026-02-30').success,false);});
if(!process.env.CAPACITY_TEST_DATABASE_URL)test('Capacity PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.CAPACITY_TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55442'&&url.pathname==='/flowlio_capacity_test');
 const {Pool}=require('pg');const pool=new Pool({connectionString:url.toString()});const service=require('../src/modules/capacity/service').createCapacity(pool);
 const owner={id:'owner',role:'user',organizationId:'org-a',isOrganizationOwner:true};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool)});
 beforeEach(async()=>{await pool.query(`truncate users,organizations cascade;
 insert into users(id,name,email,role,status,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values ('owner','Owner','owner@example.test','user','active',true,false,false,'UTC',now(),now()),('member','Member','member@example.test','operator','active',true,false,false,'UTC',now(),now()),('foreign','Foreign','foreign@example.test','user','active',true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,created_at,updated_at) values ('org-a','A','a',now(),now()),('org-b','B','b',now(),now());
 insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m1','owner','org-a','owner','active',now(),now()),('m2','member','org-a','member','active',now(),now()),('m3','foreign','org-b','member','active',now(),now());
 insert into projects(id,name,project_number,organization_id,created_by,visibility,created_at,updated_at) values ('project','Project','1','org-a','owner','private',now(),now());
 insert into tasks(id,title,project_id,assigned_to,created_by,visibility,status,estimated_hours,start_date,end_date,created_at,updated_at) values ('task','Design','project','member','owner','private','todo',14,'2026-09-21','2026-10-04',now(),now());`);});
 after(()=>pool.end());
 test('unknown capacity is not reported as free time; saving capacity and team drives overload and filters',async()=>{let r=await service.report(owner,{week:'2026-09-21'});let m=r.members.find(m=>m.id==='member');assert.equal(m.plannedMinutes,420);assert.equal(m.remainingMinutes,null);await service.save(owner,'member',{weeklyMinutes:300,team:'Design'});r=await service.report(owner,{week:'2026-09-21',team:'Design'});assert.equal(r.members.length,1);assert.equal(r.members[0].overloaded,true);assert.equal(r.members[0].remainingMinutes,-120);});
 test('rejects foreign members, ordinary members, invalid weeks and invalid capacity',async()=>{await assert.rejects(service.save(owner,'foreign',{weeklyMinutes:60,team:''}),{code:'MEMBER_NOT_FOUND'});await assert.rejects(service.report({...owner,isOrganizationOwner:false},{week:'2026-09-21'}),{code:'FORBIDDEN'});await assert.rejects(service.report(owner,{week:'2026-02-30'}),{code:'INVALID_WEEK'});await assert.rejects(service.save(owner,'member',{weeklyMinutes:-1,team:''}),{code:'INVALID_CAPACITY'});});
 test('inaccessible tasks do not leak details or claim spare capacity',async()=>{await service.save(owner,'member',{weeklyMinutes:2400,team:''});await pool.query("update tasks set created_by='member';update projects set created_by='member'");const r=await service.report(owner,{week:'2026-09-21'});assert.equal(r.hiddenTasks,1);const m=r.members.find(m=>m.id==='member');assert.equal(m.tasks.length,0);assert.equal(m.remainingMinutes,null);});
 test('dependencies, unknown dates, unestimated and unassigned work are visible without inventing effort',async()=>{await pool.query("update tasks set start_after='missing',estimated_hours=null,start_date=null");let r=await service.report(owner,{week:'2026-09-21'});const m=r.members.find(m=>m.id==='member');assert.equal(m.blocked,1);assert.equal(m.unestimated,1);assert.equal(m.unscheduled,1);assert.equal(m.remainingMinutes,null);await pool.query('update tasks set assigned_to=null');r=await service.report(owner,{week:'2026-09-21'});assert.equal(r.unassigned,1);});
 test('inactive memberships are excluded and cannot be configured',async()=>{await pool.query("update user_organizations set status='inactive' where user_id='member'");assert.equal((await service.report(owner,{week:'2026-09-21'})).members.length,1);await assert.rejects(service.save(owner,'member',{weeklyMinutes:60,team:''}),{code:'MEMBER_NOT_FOUND'});});
}
