const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
if(!process.env.CLIENT_PENDING_TEST_DATABASE_URL)test('Client pending PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.CLIENT_PENDING_TEST_DATABASE_URL);assert.ok(url.hostname==='127.0.0.1'&&url.port==='55442'&&url.pathname==='/flowlio_client_pending_test');
 const {Pool}=require('pg');const pool=new Pool({connectionString:url.toString()});const service=require('../src/modules/client-pending/service').createClientPending(pool);
 const {scheduleClientReminders,deliverClientReminder}=require('../src/modules/client-pending/reminders');
 const owner={id:'owner',role:'user',organizationId:'org',isOrganizationOwner:true};const client={id:'client-user',role:'client',organizationId:'org'};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool);});
 beforeEach(async()=>{await pool.query(`truncate business_audit_events,durable_jobs,users,organizations cascade;
 insert into users(id,name,email,role,status,is_organization_owner,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values ('owner','Owner','owner@example.test','user','active',true,true,false,false,'UTC',now(),now()),('client-user','Client','client@example.test','client','active',false,true,false,false,'UTC',now(),now()),('foreign','Other','other@example.test','client','active',false,true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,status,subscription_status,created_at,updated_at) values('org','Org','org','active','active',now(),now()),('other','Other','other','active','active',now(),now());
 insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('member','owner','org','owner','active',now(),now());
 insert into clients(id,name,email,organization_id,created_by,user_id,portal_access_enabled,created_at,updated_at) values('client','Client','client@example.test','org','owner','client-user',true,now(),now()),('other-client','Other','other@example.test','org','owner','foreign',true,now(),now());
 insert into projects(id,name,project_number,organization_id,client_id,created_by,visibility,budget,start_date,end_date,created_at,updated_at) values('project','Project','1','org','client','owner','private',1000,'2026-09-01','2026-10-01',now(),now());`);});
 after(()=>pool.end());
 async function request(extra={}){const d={id:randomUUID(),projectId:'project',kind:'question',title:'Confirm content',description:'Please review the copy.',questions:[],dependencies:[],assignedTo:'owner',dueDate:null,timezone:'UTC',reminderHours:0,reminderChannel:'internal',...extra};await service.create(owner,d);return d;}
 const response=(extra={})=>({key:randomUUID(),revision:0,action:'respond',message:'Looks good',answers:{},fileIds:[],...extra});
 const action=(name,revision=0,reason='Reviewed')=>({key:randomUUID(),revision,action:name,reason});
 async function scan(){const c=await pool.connect();try{await c.query('begin');await scheduleClientReminders(c,'org');await c.query('commit');}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
 async function deliver(id,send=async()=>{throw Error('Unexpected external send')}){const c=await pool.connect();try{return await deliverClientReminder(c,id,send)}finally{c.release()}}
 async function receipt(){await scan();return(await pool.query('select * from client_request_reminders order by created_at desc limit 1')).rows[0];}
 test('reads do not complete requests; responses require explicit team confirmation',async()=>{const r=await request();assert.equal((await service.list(client,{})).items[0].state,'open');assert.equal((await service.detail(client,r.id)).request.state,'open');await assert.rejects(service.mutate(owner,r.id,action('complete')),{code:'RESPONSE_REQUIRED'});await service.mutate(client,r.id,response());assert.equal((await service.list(owner,{state:'answered'})).items[0].responsible,'Owner');await service.mutate(owner,r.id,action('complete',1));assert.equal((await service.detail(client,r.id)).request.state,'completed');});
 test('creation and response retries are idempotent and changed keys fail',async()=>{const r=await request();await service.create(owner,r);await assert.rejects(service.create(owner,{...r,title:'Changed'}),{code:'REQUEST_CONFLICT'});const body=response();await Promise.all([service.mutate(client,r.id,body),service.mutate(client,r.id,body)]);assert.equal((await service.detail(client,r.id)).responses.length,1);await assert.rejects(service.mutate(client,r.id,{...body,message:'Changed'}),{code:'REQUEST_CONFLICT'});});
 test('tenant, client and private project boundaries apply to every read',async()=>{const r=await request();for(const a of [{...owner,organizationId:'other'},{...client,id:'foreign'},{...owner,id:'foreign'}]){assert.equal((await service.list(a,{})).items.length,0);await assert.rejects(service.detail(a,r.id));await assert.rejects(service.files(a,r.id));await assert.rejects(service.mutate(a,r.id,response()));}await assert.rejects(service.list({...owner,isOrganizationOwner:false},{}),{code:'FORBIDDEN'});await assert.rejects(service.create(client,r),{code:'FORBIDDEN'});await assert.rejects(service.mutate(client,r.id,action('cancel')),{code:'FORBIDDEN'});await assert.rejects(service.mutate(owner,r.id,response()),{code:'FORBIDDEN'});});
 test('client reassignment and portal disable revoke access without exposing old responses',async()=>{const r=await request();await pool.query("update clients set portal_access_enabled=false where id='client'");await assert.rejects(service.detail(client,r.id),{code:'PROJECT_NOT_FOUND'});await assert.rejects(request(),{code:'CLIENT_REQUIRED'});await pool.query("update projects set client_id='other-client'");assert.equal((await service.list({...client,id:'foreign'},{})).items.length,0);await assert.rejects(service.detail({...client,id:'foreign'},r.id),{code:'REQUEST_NOT_FOUND'});await service.mutate(owner,r.id,action('cancel'));});
 test('dependencies block responses until confirmed, and reopening restores the block',async()=>{const a=await request(),b=await request({dependencies:[a.id]});assert.equal((await service.detail(client,b.id)).blocked,true);await assert.rejects(service.mutate(client,b.id,response()),{code:'DEPENDENCY_PENDING'});await service.mutate(client,a.id,response());await assert.rejects(service.mutate(client,b.id,response()),{code:'DEPENDENCY_PENDING'});await service.mutate(owner,a.id,action('complete',1));await service.mutate(client,b.id,response());await service.mutate(owner,a.id,action('reopen',2));await assert.rejects(service.mutate(owner,b.id,action('complete',1)),{code:'DEPENDENCY_PENDING'});await assert.rejects(request({dependencies:['missing']}),{code:'INVALID_DEPENDENCY'});});
 test('briefings validate required answers, choices and unknown fields',async()=>{const r=await request({kind:'briefing',questions:[{id:'color',label:'Color',type:'choice',required:true,options:['Blue','Green']}]});for(const answers of [{},{color:'Red'},{color:'Blue',unknown:'x'}])await assert.rejects(service.mutate(client,r.id,response({answers})),{code:'INVALID_ANSWERS'});await service.mutate(client,r.id,response({answers:{color:'Blue'}}));await assert.rejects(request({kind:'briefing',questions:[{id:'constructor',label:'Name',type:'text',required:true,options:[]}]}),{code:'INVALID_INPUT'});});
 test('question and file requests require matching content',async()=>{const q=await request(),f=await request({kind:'file'});await assert.rejects(service.mutate(client,q.id,response({message:''})),{code:'ANSWER_REQUIRED'});await assert.rejects(service.mutate(client,f.id,response()),{code:'ANSWER_REQUIRED'});});
 test('attachment versions are frozen and foreign client files are rejected',async()=>{await pool.query(`insert into files(id,name,organization_id,project_id,client_id,uploaded_by,created_at,updated_at) values('file','Brief','org','project','client','owner',now(),now());insert into file_versions(id,file_id,url,name,size,type,version_number,uploaded_by,created_at) values('v1','file','https://example.test/brief.pdf','Brief',12,'application/pdf',1,'owner',now())`);const r=await request({kind:'file'});await service.mutate(client,r.id,response({fileIds:['file']}));await pool.query(`insert into file_versions(id,file_id,url,name,size,type,version_number,uploaded_by,created_at) values('v2','file','https://example.test/new.pdf','New',20,'application/pdf',2,'owner',now())`);assert.equal((await service.detail(client,r.id)).responses[0].attachments[0].versionId,'v1');const other=await request();await pool.query("update files set client_id='other-client'");assert.deepEqual(await service.files(client,other.id),[]);await assert.rejects(service.mutate(client,other.id,response({fileIds:['file']})),{code:'INVALID_FILES'});});
 test('cancel and reopen need reasons; stale submissions cannot overwrite new cycles',async()=>{const r=await request();await assert.rejects(service.mutate(owner,r.id,action('cancel',0,'')),{code:'REASON_REQUIRED'});await service.mutate(client,r.id,response());await service.mutate(owner,r.id,action('reopen',1,'Please revise'));await assert.rejects(service.mutate(client,r.id,response()),{code:'VERSION_CHANGED'});await service.mutate(client,r.id,response({revision:2,message:'Revised'}));const d=await service.detail(client,r.id);assert.equal(d.responses.length,2);assert.equal(d.request.cycle,2);assert.equal(d.responses[1].message,'Looks good');});
 test('local deadline ends at next midnight including DST; invalid zones fail',async()=>{const r=await request({dueDate:'2026-03-08',timezone:'America/New_York'});assert.equal((await service.detail(owner,r.id)).request.due_at.toISOString(),'2026-03-09T04:00:00.000Z');await assert.rejects(request({timezone:'Invalid/Zone'}),{code:'INVALID_TIMEZONE'});await assert.rejects(request({dueDate:'2026-02-30'}),{code:'INVALID_INPUT'});});
 test('queue merges scope approval without money or duplicated decision state',async()=>{const s=require('../src/modules/scope/service').createScopeChanges(pool);const id=randomUUID();await s.create(owner,'project',{id,title:'More work',description:'Extra page',fileIds:[]});await s.transition(owner,'project',id,{action:'estimate',revision:0,classification:'additional',estimatedHours:'2',amount:'987.65',currency:'BRL',endDate:null,note:'Estimate'});const rows=(await service.list(client,{})).items;assert.equal(rows.length,1);assert.equal(rows[0].kind,'scope');assert.ok(rows[0].href.endsWith('changeId='+id));assert.ok(!JSON.stringify(rows).includes('987.65'));await s.transition(client,'project',id,{action:'decide',revision:1,state:'approved',comment:''});assert.equal((await service.list(client,{})).items.length,0);assert.equal((await service.list(client,{state:'completed'})).items[0].sourceState,'approved');});
 test('reminder scan is idempotent and stops at three attempts',async()=>{const r=await request({dueDate:'2020-01-01',reminderHours:24});await Promise.all([scan(),scan()]);assert.equal((await pool.query('select count(*)::int n from client_request_reminders')).rows[0].n,1);for(let i=0;i<4;i++){await pool.query('update client_requests set reminder_next_at=now()-interval \'1 hour\' where id=$1',[r.id]);await scan();}assert.equal((await pool.query('select count(*)::int n from client_request_reminders')).rows[0].n,3);});
 test('answered, cancelled and reopened cycles suppress queued reminders',async()=>{for(const state of ['answer','cancel','reopen']){await pool.query('truncate client_requests cascade');const r=await request({dueDate:'2020-01-01',reminderHours:24});const x=await receipt();if(state==='answer')await service.mutate(client,r.id,response());else{await service.mutate(owner,r.id,action('cancel'));if(state==='reopen')await service.mutate(owner,r.id,action('reopen',1));}await deliver(x.id);assert.equal((await pool.query('select outcome from client_request_reminders where id=$1',[x.id])).rows[0].outcome,'cancelled');}assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);});
 test('internal reminder targets current client once with a safe portal link',async()=>{const r=await request({dueDate:'2020-01-01',reminderHours:24});const x=await receipt();await deliver(x.id);await deliver(x.id);const rows=(await pool.query('select * from notifications')).rows;assert.equal(rows.length,1);assert.equal(rows[0].user_id,client.id);assert.equal(rows[0].data.clientRequestId,r.id);});
 test('revoked author permissions stop reminder delivery',async()=>{await request({dueDate:'2020-01-01',reminderHours:24});const x=await receipt();await pool.query("update user_organizations set status='inactive'");await deliver(x.id);assert.equal((await pool.query('select outcome from client_request_reminders')).rows[0].outcome,'permission_revoked');});
 test('external reminders require opt-in and unconfirmed deliveries throw for durable uncertain handling',async()=>{await pool.query("update users set notification_preferences='{}' where id='client-user'");await request({dueDate:'2020-01-01',reminderHours:24,reminderChannel:'email'});const x=await receipt();await deliver(x.id);assert.equal((await pool.query('select outcome from client_request_reminders where id=$1',[x.id])).rows[0].outcome,'preferences_disabled');await pool.query(`update users set notification_preferences='{"emailNotifications":true}' where id='client-user'`);await request({dueDate:'2020-01-01',reminderHours:24,reminderChannel:'email'});const y=await receipt();await assert.rejects(deliver(y.id,async()=>false),/unconfirmed/);});
 test('delivery links select the source review and invalidate changed milestone versions',async()=>{await pool.query("insert into project_milestones(id,project_id,organization_id,title,status,position,due_date,created_at,updated_at) values('milestone','project','org','Design','in_progress',0,'2026-10-15',now(),now())");const delivery=require('../src/modules/delivery/service').createDeliveryReviews(pool);const m=(await delivery.list(owner,'project')).milestones[0];const r=await delivery.request(owner,'project',{milestoneId:m.id,version:m.version,note:'Review design'});const row=(await service.list(client,{})).items[0];assert.equal(row.stale,false);assert.ok(row.href.includes('reviewId='+r.id));assert.equal((await delivery.list(client,'project',2,r.id)).reviews[0].id,r.id);await pool.query("update project_milestones set title='Changed'");assert.equal((await service.list(client,{})).items[0].stale,true);await assert.rejects(delivery.decide(client,'project',r.id,{version:m.version,state:'approved',comment:''}),{code:'SOURCE_CHANGED'});});

}
