const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');
if(!process.env.DELIVERY_TEST_DATABASE_URL)test('Delivery PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.DELIVERY_TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55442'&&url.pathname==='/flowlio_delivery_test');
 const {Pool}=require('pg');const pool=new Pool({connectionString:url.toString()});const service=require('../src/modules/delivery/service').createDeliveryReviews(pool);
 const owner={id:'owner',role:'user',organizationId:'org-a',isOrganizationOwner:true};const client={id:'client-user',role:'client',organizationId:'org-a'};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool)});
 beforeEach(async()=>{await pool.query(`truncate users,organizations cascade;
 insert into users(id,name,email,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values ('owner','Owner','owner@example.test',true,false,false,'UTC',now(),now()),('client-user','Client','client@example.test',true,false,false,'UTC',now(),now()),('other','Other','other@example.test',true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,created_at,updated_at) values ('org-a','A','a',now(),now()),('org-b','B','b',now(),now());
 insert into clients(id,name,email,organization_id,user_id,created_by,created_at,updated_at) values ('client','Client','client@example.test','org-a','client-user','owner',now(),now()),('other-client','Other','other@example.test','org-a','other','owner',now(),now());
 insert into projects(id,name,project_number,organization_id,client_id,created_by,visibility,created_at,updated_at) values ('project','Project','1','org-a','client','owner','private',now(),now());
 insert into project_milestones(id,project_id,organization_id,title,status,position,created_at,updated_at) values('milestone','project','org-a','Design','in_progress',0,now(),now());`);});
 after(()=>pool.end());
 async function input(){const row=(await service.list(owner,'project')).milestones[0];return{milestoneId:row.id,version:row.version,note:'Review the agreed design milestone'};}
 async function requested(){const body=await input();const r=await service.request(owner,'project',body);return{id:r.id,version:body.version};}
 test('concurrent request retries create one receipt and one activity',async()=>{const body=await input();const rows=await Promise.all(Array.from({length:12},()=>service.request(owner,'project',body)));assert.equal(new Set(rows.map(r=>r.id)).size,1);assert.equal((await pool.query('select count(*)::int n from recent_activities')).rows[0].n,1);const view=await service.list(client,'project');assert.equal(view.canRequest,false);assert.equal(view.reviews[0].canDecide,true);});
 test('client decisions are idempotent and competing decisions cannot overwrite history',async()=>{const r=await requested();const body={version:r.version,state:'approved',comment:'Accepted'};const results=await Promise.all(Array.from({length:10},()=>service.decide(client,'project',r.id,body)));assert.equal(results.filter(r=>!r.existing).length,1);await assert.rejects(service.decide(client,'project',r.id,{...body,state:'changes_requested',comment:'Change it'}),{code:'ALREADY_DECIDED'});const view=await service.list(owner,'project');assert.equal(view.reviews[0].state,'approved');assert.equal(view.reviews[0].decidedBy,'Client');assert.equal((await pool.query('select status from project_milestones')).rows[0].status,'in_progress');});
 test('changed or removed milestones reject stale decisions and preserve the original receipt',async()=>{const r=await requested();await pool.query("update project_milestones set title='New scope',updated_at=now()");assert.equal((await service.list(client,'project')).reviews[0].stale,true);await assert.rejects(service.decide(client,'project',r.id,{version:r.version,state:'approved'}),{code:'SOURCE_CHANGED'});assert.equal((await service.list(owner,'project')).reviews[0].title,'Design');await pool.query("delete from project_milestones");await assert.rejects(service.decide(client,'project',r.id,{version:r.version,state:'approved'}),{code:'SOURCE_CHANGED'});});
 test('only the assigned project client can decide and foreign organizations cannot inspect history',async()=>{const r=await requested();const body={version:r.version,state:'approved'};for(const actor of [owner,{...client,id:'other'},{...client,organizationId:'org-b'}])await assert.rejects(service.decide(actor,'project',r.id,body));await assert.rejects(service.list({...owner,organizationId:'org-b'},'project'));await assert.rejects(service.request(client,'project',await input()),{code:'FORBIDDEN'});});
 test('changing the project client does not leak previous client receipts to the replacement',async()=>{await requested();await pool.query("update projects set client_id='other-client'");await assert.rejects(service.list(client,'project'));assert.equal((await service.list({...client,id:'other'},'project')).reviews.length,0);assert.equal((await service.list(owner,'project')).reviews[0].stale,true);});
 test('requesting changes requires a comment; editing the milestone permits a new review',async()=>{const r=await requested();await assert.rejects(service.decide(client,'project',r.id,{version:r.version,state:'changes_requested',comment:' '}),{code:'INVALID_DECISION'});await service.decide(client,'project',r.id,{version:r.version,state:'changes_requested',comment:'Adjust spacing'});await pool.query("update project_milestones set title='Design revised',updated_at=now()");const next=await requested();assert.notEqual(next.id,r.id);const view=await service.list(client,'project');assert.equal(view.reviews.length,2);assert.ok(view.reviews.some(row=>row.comment==='Adjust spacing'));});
 test('a failed activity write rolls back the review request',async()=>{const body=await input();await pool.query("create function fail_delivery_activity() returns trigger language plpgsql as $$ begin raise exception 'test'; end $$;create trigger fail_delivery before insert on recent_activities for each row execute function fail_delivery_activity()");try{await assert.rejects(service.request(owner,'project',body));assert.equal((await pool.query('select count(*)::int n from delivery_reviews')).rows[0].n,0);}finally{await pool.query('drop trigger fail_delivery on recent_activities;drop function fail_delivery_activity()')}});
 test('a request cannot publish a version changed since selection',async()=>{const body=await input();await pool.query("update project_milestones set title='Different scope'");await assert.rejects(service.request(owner,'project',body),{code:'SOURCE_CHANGED'});});
}
