const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');
const {createProfitability,toCents,fromCents,timeValue,reportPeriod,financialSettings}=require('../src/modules/profitability/service');
test('money uses integer cents and rounds per time entry',()=>{assert.equal(fromCents(toCents('0.10')+toCents('0.20')),'0.30');assert.equal(fromCents(timeValue(1,'10.00')),'0.17');assert.equal(fromCents(toCents('-1.01')),'-1.01');assert.throws(()=>timeValue(60,'-1'));assert.throws(()=>toCents('NaN'));});
test('period and assumptions reject invalid dates, currency, costs and implicit currency',()=>{for(const period of [{from:'2026-02-29',to:'2026-03-01'},{from:'2026-07-02',to:'2026-07-01'},{from:'2020-01-01',to:'2026-01-01'}])assert.equal(reportPeriod.safeParse(period).success,false);for(const settings of [{currency:'XYZ',hourlyCost:'10',confirmCurrency:true},{currency:'USD',hourlyCost:'-1',confirmCurrency:true},{currency:'USD',hourlyCost:'10'}])assert.equal(financialSettings.safeParse(settings).success,false);});
if(!process.env.PROFITABILITY_TEST_DATABASE_URL)test('Profitability PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.PROFITABILITY_TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55442'&&url.pathname==='/flowlio_profitability_test');
 const {Pool}=require('pg');const pool=new Pool({connectionString:url.toString()});const service=createProfitability(pool);
 const actor={id:'owner',role:'user',organizationId:'org-a',isOrganizationOwner:true};const period={from:'2026-07-01',to:'2026-07-31'};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool)});
 beforeEach(async()=>{await pool.query(`truncate users,organizations cascade;
 insert into users(id,name,email,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values ('owner','Owner','owner@example.test',true,false,false,'UTC',now(),now()),('other','Other','other@example.test',true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,created_at,updated_at) values ('org-a','A','a',now(),now()),('org-b','B','b',now(),now());
 insert into projects(id,name,project_number,organization_id,created_by,visibility,created_at,updated_at) values ('project','Project','1','org-a','owner','private',now(),now());
 insert into revenue_entries(id,organization_id,date,amount,currency,category,source,project_id,created_by,created_at,updated_at) values ('revenue','org-a','2026-07-05',1000,'USD','service','manual','project','owner',now(),now());
 insert into project_expenses(id,project_id,amount,category,description,date,created_by,created_at,updated_at) values ('expense','project',100,'other','Cost','2026-07-05','owner',now(),now());
 insert into time_entries(id,user_id,project_id,start_time,end_time,duration,hourly_rate,billable,status,created_at,updated_at) values ('time','owner','project','2026-07-05 10:00','2026-07-05 12:00',120,80,true,'completed',now(),now());`);});
 after(()=>pool.end());const configure=(hourlyCost='25')=>service.save(actor,'project',{currency:'USD',hourlyCost,confirmCurrency:true});
 test('report requires explicit assumptions and separates revenue, labor and unbilled sales',async()=>{assert.equal((await service.report(actor,'project',period)).settings,null);await configure();const r=await service.report(actor,'project',period);assert.equal(r.revenue,'1000.00');assert.equal(r.expenses,'100.00');assert.equal(r.laborCost,'50.00');assert.equal(r.estimatedProfit,'850.00');assert.equal(r.unbilledValue,'160.00');assert.equal(r.complete,true);});
 test('period boundaries exclude revenue, expenses and time outside recorded dates',async()=>{await configure();const r=await service.report(actor,'project',{from:'2026-07-06',to:'2026-07-06'});assert.equal(r.revenue,'0.00');assert.equal(r.expenses,'0.00');assert.equal(r.minutes,0);assert.equal(r.estimatedProfit,'0.00');});
 test('missing labor is unknown, not free, and missing sales rate stays unpriced',async()=>{await configure(null);await pool.query("update time_entries set hourly_rate=null");const r=await service.report(actor,'project',period);assert.equal(r.laborCost,null);assert.equal(r.estimatedProfit,null);assert.equal(r.unpricedMinutes,120);assert.equal(r.unbilledValue,'0.00');});
 test('other currencies are disclosed and never summed into profit',async()=>{await configure();await pool.query("update revenue_entries set currency='EUR'");const r=await service.report(actor,'project',period);assert.equal(r.revenue,'0.00');assert.equal(r.otherCurrencies[0].amount,'1000.00');assert.equal(r.estimatedProfit,null);});
 test('owners cannot cross organizations or private projects and managers cannot access internal costs',async()=>{await configure();for(const a of [{...actor,organizationId:'org-b'},{...actor,id:'other'},{...actor,isOrganizationOwner:false,isOrganizationManager:true}]){await assert.rejects(service.report(a,'project',period));await assert.rejects(service.save(a,'project',{currency:'USD',hourlyCost:'1',confirmCurrency:true}));}});
 test('unfinished time and inaccessible task time make totals incomplete',async()=>{await configure();await pool.query("update time_entries set end_time=null,status='active'");let r=await service.report(actor,'project',period);assert.equal(r.incompleteEntries,1);assert.equal(r.estimatedProfit,null);
 await pool.query("insert into tasks(id,title,project_id,created_by,visibility,created_at,updated_at) values('hidden','Hidden','project','other','private',now(),now());update time_entries set task_id='hidden',end_time='2026-07-05 12:00',status='completed'");r=await service.report(actor,'project',period);assert.equal(r.hiddenEntries,1);assert.equal(r.minutes,0);assert.equal(r.estimatedProfit,null);});
}
