const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {availability,compare}=require('../src/modules/scenarios/calculation');
test('overlapping absences subtract calendar days once and preserve unknown capacity',()=>{const a=[{startDate:'2026-09-21',endDate:'2026-09-23'},{startDate:'2026-09-23',endDate:'2026-09-25'}];assert.deepEqual(availability(420,a,'2026-09-21'),{availableMinutes:120,absenceMinutes:300});assert.deepEqual(availability(null,a,'2026-09-21'),{availableMinutes:null,absenceMinutes:null});assert.equal(availability(0,a,'2026-09-21').availableMinutes,0);assert.equal(availability(420,[{startDate:'2026-09-01',endDate:'2026-10-01'}],'2026-09-21').availableMinutes,0);});
test('weekly comparison replaces task allocation without double counting and keeps hypothetical work separate',()=>{const base={members:[{id:'u',name:'User',weeklyMinutes:420,team:''}],absences:[],hiddenTasks:0,excludedParents:0,tasks:[{id:'task',title:'Task',projectId:'p',projectName:'P',assignedTo:'u',startDate:'2026-09-21',endDate:'2026-10-04',estimatedHours:'14',blocked:true}]};const changes=[{key:'a',type:'task',taskId:'task',assignedTo:'u',startDate:'2026-09-28',endDate:'2026-10-04'}];let rows=compare(base,changes,'2026-09-21',2);assert.equal(rows[0].before.members[0].plannedMinutes,420);assert.equal(rows[0].after.members[0].plannedMinutes,0);assert.equal(rows[1].after.members[0].plannedMinutes,840);assert.equal(rows[1].after.members[0].blocked,1);changes.push({key:'b',type:'proposal',title:'New project',assignedTo:null,startDate:'2026-09-21',endDate:'2026-09-27',estimatedMinutes:null});rows=compare(base,changes,'2026-09-21',2);assert.equal(rows[0].after.unassigned,1);assert.equal(rows[0].after.members[0].remainingMinutes,null);assert.equal(base.tasks[0].startDate,'2026-09-21');});
if(!process.env.SCENARIO_TEST_DATABASE_URL)test('Scenarios PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.SCENARIO_TEST_DATABASE_URL);assert.ok(url.hostname==='127.0.0.1'&&url.port==='55442'&&url.pathname==='/flowlio_scenario_test');const {Pool}=require('pg');const pool=new Pool({connectionString:url.toString()});const service=require('../src/modules/scenarios/service').createScenarios(pool);const capacity=require('../src/modules/capacity/service').createCapacity(pool);
 const owner={id:'owner',role:'user',organizationId:'org',isOrganizationOwner:true};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool);});
 beforeEach(async()=>{await pool.query(`truncate business_audit_events,users,organizations cascade;
 insert into users(id,name,email,role,status,is_organization_owner,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values('owner','Owner','owner@example.test','user','active',true,true,false,false,'UTC',now(),now()),('member','Member','member@example.test','operator','active',false,true,false,false,'UTC',now(),now()),('other','Other','other@example.test','user','active',true,true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,created_at,updated_at) values('org','Org','org',now(),now()),('other-org','Other','other',now(),now());
 insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m1','owner','org','owner','active',now(),now()),('m2','member','org','member','active',now(),now()),('m3','other','other-org','owner','active',now(),now());
 insert into projects(id,name,project_number,organization_id,created_by,visibility,created_at,updated_at) values('project','Project','1','org','owner','public',now(),now());
 insert into tasks(id,title,project_id,assigned_to,created_by,visibility,status,estimated_hours,start_date,end_date,created_at,updated_at) values('task','Design','project','member','owner','private','todo',14,'2026-09-21','2026-10-04',now(),now());
 insert into member_capacity(organization_id,user_id,weekly_minutes,team,updated_by) values('org','member',420,'Design','owner');`);});
 after(()=>pool.end());
 async function scenario(){const d={id:randomUUID(),title:'Next month',week:'2026-09-23',weeks:2};await service.create(owner,d);return d;}
 const move=(extra={})=>({key:randomUUID(),type:'task',taskId:'task',assignedTo:'member',startDate:'2026-09-28',endDate:'2026-10-04',...extra});
 const application=(changes,extra={})=>({key:randomUUID(),revision:1,selected:changes.map(c=>c.key),confirm:true,...extra});
 async function task(){return(await pool.query('select * from tasks where id=\'task\'')).rows[0];}
 async function absence(extra={}){const d={id:randomUUID(),userId:'member',startDate:'2026-09-21',endDate:'2026-09-23',kind:'vacation',...extra};await service.absenceCreate(owner,d);return d;}
 test('draft creation, simulation and GET never change tasks',async()=>{const original=await task(),s=await scenario(),change=move();await service.save(owner,s.id,{revision:0,changes:[change]});const view=await service.detail(owner,s.id);assert.equal(view.week,'2026-09-21');assert.equal(view.comparison[0].after.members.find(m=>m.id==='member').plannedMinutes,0);assert.deepEqual(await task(),original);assert.equal(view.stale,false);await service.create(owner,s);assert.equal((await service.list(owner)).length,1);});
 test('explicit apply changes selected tasks once and records audit',async()=>{const s=await scenario(),change=move();await service.save(owner,s.id,{revision:0,changes:[change]});const body=application([change]);await service.apply(owner,s.id,body);const first=await task();await service.apply(owner,s.id,body);assert.deepEqual(await task(),first);assert.equal((await pool.query("select to_char(start_date,'YYYY-MM-DD') d from tasks where id='task'")).rows[0].d,'2026-09-28');assert.equal((await service.detail(owner,s.id)).state,'applied');assert.equal((await pool.query("select count(*)::int n from business_audit_events where action='capacity.scenario_applied'")).rows[0].n,1);});
 test('hypothetical work is compared but never creates a task or project',async()=>{const s=await scenario(),c={key:randomUUID(),type:'proposal',title:'New website',assignedTo:'member',startDate:'2026-09-21',endDate:'2026-09-27',estimatedMinutes:600};await service.save(owner,s.id,{revision:0,changes:[c]});assert.equal((await service.detail(owner,s.id)).comparison[0].after.members.find(m=>m.id==='member').plannedMinutes,1020);await assert.rejects(service.apply(owner,s.id,application([c])),{code:'INVALID_SELECTION'});assert.equal((await pool.query('select count(*)::int n from tasks')).rows[0].n,1);});
 test('external planning changes require explicit refresh and clear the old proposal',async()=>{const s=await scenario(),c=move();await service.save(owner,s.id,{revision:0,changes:[c]});await pool.query("update tasks set estimated_hours=28 where id='task'");assert.equal((await service.detail(owner,s.id)).stale,true);await assert.rejects(service.apply(owner,s.id,application([c])),{code:'PLAN_CHANGED'});await service.refresh(owner,s.id,{revision:1,confirm:true});const d=await service.detail(owner,s.id);assert.equal(d.stale,false);assert.deepEqual(d.changes,[]);assert.equal(d.base.tasks[0].estimatedHours,'28.00');});
 test('new work, changed capacity and changed absences all invalidate saved snapshots',async()=>{for(const sql of ["insert into tasks(id,title,project_id,created_by,status,created_at,updated_at) values('new','New','project','owner','todo',now(),now())","update member_capacity set weekly_minutes=840","insert into capacity_absences(id,organization_id,user_id,start_date,end_date,kind,created_by) values('a','org','member','2026-09-21','2026-09-22','vacation','owner')"]){const s=await scenario(),c=move();await service.save(owner,s.id,{revision:0,changes:[c]});await pool.query(sql);await assert.rejects(service.apply(owner,s.id,application([c])),{code:'PLAN_CHANGED'});}});
 test('foreign organizations, other authors, clients and ordinary users cannot access drafts',async()=>{const s=await scenario();for(const a of [{...owner,organizationId:'other-org'},{...owner,id:'other'}]){assert.equal((await service.list(a)).length,0);await assert.rejects(service.detail(a,s.id),{code:'SCENARIO_NOT_FOUND'});}for(const a of [{...owner,role:'client'},{...owner,isOrganizationOwner:false}])await assert.rejects(service.create(a,{...s,id:randomUUID()}),{code:'FORBIDDEN'});});
 test('revoked task access does not expose stored titles and can only recover through refresh',async()=>{await pool.query("update tasks set title='Confidential task title'");const s=await scenario();await pool.query("update tasks set created_by='member'");await assert.rejects(service.detail(owner,s.id),{code:'SCENARIO_ACCESS_CHANGED'});await service.refresh(owner,s.id,{revision:0,confirm:true});const d=await service.detail(owner,s.id);assert.equal(d.base.tasks.length,0);assert.equal(d.base.hiddenTasks,1);assert.ok(!JSON.stringify(d).includes('Confidential task title'));assert.equal(d.comparison[0].after.members[0].remainingMinutes,null);});
 test('assignment never grants access to a private project implicitly',async()=>{await pool.query("update projects set visibility='private'");const s=await scenario();await assert.rejects(service.save(owner,s.id,{revision:0,changes:[move()]}),{code:'PROJECT_ACCESS_REQUIRED'});await service.save(owner,s.id,{revision:0,changes:[move({assignedTo:'owner'})]});});
 test('absence overlap affects official capacity once and recurring settings stay intact',async()=>{await absence();await absence({startDate:'2026-09-23',endDate:'2026-09-25'});const r=await capacity.report(owner,{week:'2026-09-21'}),m=r.members.find(m=>m.id==='member');assert.equal(m.availableMinutes,120);assert.equal(m.absenceMinutes,300);assert.equal(m.weeklyMinutes,420);const d=await service.detail(owner,(await scenario()).id);assert.equal(d.comparison[0].before.members.find(m=>m.id==='member').availableMinutes,120);assert.equal(d.comparison[0].before.members.find(m=>m.id==='owner').availableMinutes,null);});
 test('absence input rejects foreign members and invalid dates; remove checks tenant and revision',async()=>{await assert.rejects(absence({userId:'other'}),{code:'MEMBER_NOT_FOUND'});await assert.rejects(absence({endDate:'2026-02-30'}),{code:'INVALID_INPUT'});const a=await absence();await service.absenceCreate(owner,a);await assert.rejects(service.absenceRemove({...owner,organizationId:'other-org'},a.id,{revision:0}),{code:'VERSION_CHANGED'});await service.absenceRemove(owner,a.id,{revision:0});assert.equal((await service.absenceList(owner)).items.length,0);});
 test('parent estimates do not double count work already split into subtasks',async()=>{await pool.query("insert into tasks(id,title,project_id,parent_id,assigned_to,created_by,status,estimated_hours,start_date,end_date,created_at,updated_at) values('child','Child','project','task','member','owner','todo',7,'2026-09-21','2026-09-27',now(),now())");const d=await service.detail(owner,(await scenario()).id);assert.equal(d.base.excludedParents,1);assert.equal(d.base.tasks.length,1);assert.equal(d.comparison[0].before.members.find(m=>m.id==='member').plannedMinutes,420);assert.equal((await capacity.report(owner,{week:'2026-09-21'})).members.find(m=>m.id==='member').plannedMinutes,420);});
 test('a failed task update rolls back every selected task and scenario state',async()=>{await pool.query("insert into tasks(id,title,project_id,assigned_to,created_by,status,estimated_hours,start_date,end_date,created_at,updated_at) values('task2','Other task','project','member','owner','todo',7,'2026-09-21','2026-09-27',now(),now())");const s=await scenario(),changes=[move(),move({taskId:'task2'})];await service.save(owner,s.id,{revision:0,changes});const before=await task();await pool.query("create function fail_scenario_update() returns trigger language plpgsql as $$ begin if new.id='task2' then raise exception 'test failure';end if;return new;end $$;create trigger fail_scenario before update on tasks for each row execute function fail_scenario_update()");try{await assert.rejects(service.apply(owner,s.id,application(changes)),/test failure/);}finally{await pool.query('drop trigger fail_scenario on tasks;drop function fail_scenario_update()');}assert.deepEqual(await task(),before);assert.equal((await service.detail(owner,s.id)).state,'draft');});
 test('selected subset applies atomically and other proposed edits remain unapplied',async()=>{await pool.query("insert into tasks(id,title,project_id,assigned_to,created_by,status,start_date,end_date,created_at,updated_at) values('task2','Other','project','member','owner','todo','2026-09-21','2026-09-27',now(),now())");const s=await scenario(),changes=[move(),move({taskId:'task2'})];await service.save(owner,s.id,{revision:0,changes});await service.apply(owner,s.id,application([changes[0]]));assert.equal((await pool.query("select to_char(start_date,'YYYY-MM-DD') d from tasks where id='task2'")).rows[0].d,'2026-09-21');assert.deepEqual((await service.detail(owner,s.id)).appliedIds,['task']);});
 test('competing saves preserve one revision and require loser to refresh',async()=>{const s=await scenario();const outcomes=await Promise.allSettled([service.save(owner,s.id,{revision:0,changes:[move()]}),service.save(owner,s.id,{revision:0,changes:[move({assignedTo:'owner'})]})]);assert.equal(outcomes.filter(v=>v.status==='fulfilled').length,1);assert.equal((await service.detail(owner,s.id)).revision,1);});
}
