const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');
if(!process.env.WORKFLOWS_TEST_DATABASE_URL)test('Workflows PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.WORKFLOWS_TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55442'&&url.pathname==='/flowlio_workflows_test');
 const {Pool}=require('pg'),pool=new Pool({connectionString:url.toString()});const {createWorkflows,processWorkflowOrganization}=require('../src/modules/workflows/service'),service=createWorkflows(pool);
 const actor={id:'owner',role:'user',organizationId:'org-a',isOrganizationOwner:true};
 const draft={name:'Accepted delivery',trigger:'delivery_approved',projectStatus:null,title:'Delivery accepted',message:'Review the next project milestone.'};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool)});
 beforeEach(async()=>{await pool.query(`truncate business_audit_events,durable_jobs,users,organizations cascade;
 insert into users(id,name,email,role,status,is_organization_owner,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values('owner','Owner','owner@example.test','user','active',true,true,false,false,'UTC',now(),now()),('other','Other','other@example.test','user','active',true,true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,status,subscription_status,created_at,updated_at) values('org-a','A','a','active','active',now(),now()),('org-b','B','b','active','active',now(),now());
 insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m1','owner','org-a','owner','active',now(),now());
 insert into projects(id,name,project_number,organization_id,created_by,visibility,status,created_at,updated_at) values('project','Project','1','org-a','owner','private','pending',now(),now());`);});
 after(()=>pool.end());
 async function rule(){const r=await service.create(actor,draft);await service.setEnabled(actor,r.id,{enabled:true});return r.id;}
 async function event(id='event'){await pool.query("insert into recent_activities(id,organization_id,actor_id,type,action,resource,resource_id,created_at) values($1,'org-a','owner','delivery','delivery_approved','project','project',clock_timestamp())",[id]);}
 async function run(){const client=await pool.connect();try{await client.query('begin');await processWorkflowOrganization(client,'org-a');await client.query('commit')}catch(e){await client.query('rollback');throw e}finally{client.release()}}
 test('simulation reads persisted events without notifications or execution writes',async()=>{const id=await rule();await event();assert.deepEqual(await service.inspect(actor,id,true),{sampled:1,matches:1,limit:100,reasons:{}});assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);assert.equal((await service.inspect(actor,id,false)).length,0);});
 test('concurrent retries notify once and do not generate chained activity',async()=>{const id=await rule();await event();await Promise.all(Array.from({length:8},run));assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,1);assert.equal((await service.inspect(actor,id,false)).length,1);assert.equal((await pool.query('select count(*)::int n from recent_activities')).rows[0].n,1);});
 test('condition mismatch is recorded without notification',async()=>{const r=await service.create(actor,{...draft,projectStatus:'completed'});await service.setEnabled(actor,r.id,{enabled:true});await event();await run();assert.equal((await service.inspect(actor,r.id,false))[0].outcome,'condition_not_met');assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);});
 test('private projects, foreign organizations and other rule authors remain isolated',async()=>{const id=await rule();await event();await pool.query("update projects set created_by='other'");await run();assert.equal((await service.inspect(actor,id,false))[0].outcome,'inaccessible');assert.equal((await service.inspect(actor,id,true)).sampled,0);await assert.rejects(service.inspect({...actor,organizationId:'org-b'},id,false),{code:'RULE_NOT_FOUND'});await assert.rejects(service.setEnabled({...actor,id:'other'},id,{enabled:false}),{code:'RULE_NOT_FOUND'});});
 test('revoked membership pauses rule before any effect',async()=>{const id=await rule();await event();await pool.query("update user_organizations set status='inactive'");await run();assert.equal((await service.list(actor))[0].enabled,false);assert.equal((await service.inspect(actor,id,false)).length,0);assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);});
 test('paused and pre-activation events are not replayed when enabling',async()=>{const id=await rule();await service.setEnabled(actor,id,{enabled:false});await event();await run();await service.setEnabled(actor,id,{enabled:true});await run();assert.equal((await service.inspect(actor,id,false)).length,0);await event('new');await run();assert.equal((await service.inspect(actor,id,false)).length,1);});
 test('failed notification rolls back execution marker and retry succeeds once',async()=>{const id=await rule();await event();await pool.query("create function fail_workflow_notification() returns trigger language plpgsql as $$ begin raise exception 'test';end $$;create trigger fail_workflow before insert on notifications for each row execute function fail_workflow_notification()");try{await run();assert.equal((await service.inspect(actor,id,false))[0].outcome,'failed');assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0)}finally{await pool.query('drop trigger fail_workflow on notifications;drop function fail_workflow_notification()')}const receipt=(await service.inspect(actor,id,false))[0];await service.retry(actor,id,receipt.id);assert.equal((await service.inspect(actor,id,false))[0].outcome,'notified');assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,1);});
 test('members cannot configure rules and rule payload cannot choose another recipient',async()=>{await assert.rejects(service.create({...actor,isOrganizationOwner:false},draft),{code:'FORBIDDEN'});await assert.rejects(service.create(actor,{...draft,userId:'other'}),{code:'INVALID_RULE'});});
 async function activeRule(extra={}){const r=await service.create(actor,{...draft,recipientId:'owner',...extra});await service.setEnabled(actor,r.id,{enabled:true});return r.id;}
 async function count(table){return Number((await pool.query('select count(*) n from '+table)).rows[0].n);}
 async function clientFixture(){await pool.query(`insert into clients(id,name,email,organization_id,created_by,user_id,created_at,updated_at) values('client','Client','client@example.test','org-a','owner','other',now(),now());update projects set client_id='client';`);}
 test('task actions simulate without writes and concurrent workers create exactly one assigned task',async()=>{
  const id=await activeRule({actionType:'create_task'});await event();assert.equal((await service.inspect(actor,id,true)).matches,1);assert.equal(await count('tasks'),0);assert.equal(await count('workflow_executions'),0);
  await Promise.all(Array.from({length:6},run));assert.equal(await count('tasks'),1);const task=(await pool.query('select * from tasks')).rows[0];assert.equal(task.assigned_to,'owner');assert.equal(task.visibility,'private');const h=(await service.inspect(actor,id,false))[0];assert.equal(h.resourceId,task.id);assert.equal(h.outcome,'task_created');assert.equal(h.canRetry,false);await assert.rejects(service.retry(actor,id,h.id),{code:'RETRY_UNSAFE'});
 });
 test('quota failure has no effects and safe retry creates a task only after allowance is restored',async()=>{
  const id=await activeRule({actionType:'create_task'});await pool.query("update organizations set override_max_tasks=1 where id='org-a';insert into tasks(id,title,project_id,created_by,status,created_at,updated_at) values('existing','Existing','project','owner','todo',now(),now())");await event();await run();const x=(await service.inspect(actor,id,false))[0];assert.equal(x.outcome,'plan_limit');assert.equal(x.canRetry,true);await pool.query("update organizations set override_max_tasks=2 where id='org-a'");const retried=await Promise.allSettled([service.retry(actor,id,x.id),service.retry(actor,id,x.id)]);assert.equal(retried.filter(r=>r.status==='fulfilled').length,1);assert.equal(retried.find(r=>r.status==='rejected').reason.code,'RETRY_UNSAFE');assert.equal(await count('tasks'),2);assert.equal((await service.inspect(actor,id,false))[0].attempts,2);
 });
 test('foreign recipients are rejected; recipients losing project access are blocked at execution',async()=>{
  await assert.rejects(activeRule({recipientId:'other'}),{code:'RECIPIENT_UNAVAILABLE'});await pool.query("insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m2','other','org-a','member','active',now(),now())");
  const id=await activeRule({actionType:'create_task',recipientId:'other'});await event();await run();assert.equal((await service.inspect(actor,id,false))[0].outcome,'recipient_inaccessible');assert.equal(await count('tasks'),0);
 });
 test('project assignment is explicit, stays in the organization and does not emit eligible chains',async()=>{
  await pool.query("insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m2','other','org-a','member','active',now(),now())");const id=await activeRule({actionType:'assign_project',recipientId:'other'});await event();await Promise.all([run(),run()]);assert.equal((await pool.query("select assigned_to from projects where id='project'")).rows[0].assigned_to,'other');assert.equal((await service.inspect(actor,id,false)).length,1);assert.equal(await count('recent_activities'),1);
 });
 test('milestone completion trigger records actual transitions and ignores ordinary edits',async()=>{
  const id=await activeRule({trigger:'milestone_completed',actionType:'create_task'});
  await pool.query("insert into project_milestones(id,project_id,organization_id,title,status,created_at,updated_at) values('milestone','project','org-a','Design','pending',now(),now());update project_milestones set status='completed' where id='milestone';update project_milestones set title='Design complete' where id='milestone'");assert.equal(await count('workflow_events'),1);await run();assert.equal((await service.inspect(actor,id,false))[0].outcome,'task_created');
 });
 async function approvedScope(){
  await clientFixture();const s=require('../src/modules/scope/service').createScopeChanges(pool),id=require('node:crypto').randomUUID();
  await s.create(actor,'project',{id,title:'Extra page',description:'Approved addition',fileIds:[]});await s.transition(actor,'project',id,{action:'estimate',revision:0,classification:'additional',estimatedHours:'2',amount:'125.50',currency:'BRL',endDate:null,note:'Additional'});
  await s.transition({id:'other',role:'client',organizationId:'org-a'},'project',id,{action:'decide',revision:1,state:'approved',comment:''});return{s,id};
 }
 test('scope drafts deduplicate across rules and manual application, preserve currency and never issue invoices',async()=>{
  const first=await activeRule({trigger:'scope_approved',actionType:'prepare_billing'}),second=await activeRule({trigger:'scope_approved',actionType:'prepare_billing'});const{s,id}=await approvedScope();assert.equal((await service.inspect(actor,first,true)).matches,1);assert.equal(await count('workflow_billing_drafts'),0);await Promise.all([run(),run()]);
  const a=(await service.inspect(actor,first,false))[0],b=(await service.inspect(actor,second,false))[0];assert.equal(a.outcome,'billing_prepared');assert.equal(a.resourceId,b.resourceId);assert.equal(a.details.currency,'BRL');assert.equal(a.details.amount,'125.50');await s.transition(actor,'project',id,{action:'apply',revision:1,createTask:false,applyDate:false,prepareBilling:true,confirm:true});const row=(await s.list(actor,'project',{})).items[0];assert.equal(row.application.billingDraft.id,a.resourceId);assert.equal(await count('workflow_billing_drafts'),1);assert.equal(await count('invoices'),0);
 });
 test('revised approval cannot prepare an old charge and manager cannot configure financial actions',async()=>{
  await assert.rejects(activeRule({trigger:'delivery_approved',actionType:'prepare_billing'}),{code:'INVALID_RULE'});
  await assert.rejects(service.create({...actor,isOrganizationOwner:false,isOrganizationManager:true},{...draft,trigger:'scope_approved',actionType:'prepare_billing'}),{code:'FINANCIAL_ACCESS_REQUIRED'});
  const rid=await activeRule({trigger:'scope_approved',actionType:'prepare_billing'});const{s,id}=await approvedScope();await s.transition(actor,'project',id,{action:'estimate',revision:1,classification:'additional',estimatedHours:'3',amount:'250',currency:'BRL',endDate:null,note:'Revision'});await run();assert.equal((await service.inspect(actor,rid,false))[0].outcome,'source_changed');assert.equal(await count('workflow_billing_drafts'),0);
 });
 async function consumedRetainer(){
  await clientFixture();const s=require('../src/modules/retainers/service').createRetainers(pool),id=require('node:crypto').randomUUID();
  await s.create(actor,'client',{id,name:'Support',currency:'BRL',monthlyAmount:'100',includedMinutes:60,timezone:'UTC',startMonth:'2026-01',endMonth:null,renewal:'manual',carryPolicy:'expire',carryCap:0,carryMonths:0,overagePolicy:'approval',overageRate:'20',recurringId:null,confirm:true});
  await pool.query("insert into time_entries(id,user_id,project_id,client_id,start_time,end_time,duration,status,billable,hourly_rate,created_at,updated_at) values('time','owner','project','client','2026-01-15 10:00:00','2026-01-15 11:30:00',90,'completed',true,10,now(),now())");
  let p=(await s.detail(actor,'client',id,{})).period;const entries=(await s.candidates(actor,'client',id,p.id,{})).items;
  await s.mutate(actor,'client',id,{key:require('node:crypto').randomUUID(),periodId:p.id,revision:p.revision,action:'allocate',entries:entries.map(t=>({id:t.id,version:t.version}))});p=(await s.detail(actor,'client',id,{})).period;return{s,id,p};
 }
 test('consumption thresholds are emitted once per period and matching-client project is mandatory',async()=>{
  const rid=await activeRule({trigger:'retainer_80'});const{s,id,p}=await consumedRetainer();assert.equal((await pool.query("select count(*)::int n from workflow_events where trigger in ('retainer_80','retainer_100')")).rows[0].n,2);await run();assert.equal((await service.inspect(actor,rid,false))[0].outcome,'notified');
  const entry=(await s.detail(actor,'client',id,{})).entries[0];await s.mutate(actor,'client',id,{key:require('node:crypto').randomUUID(),periodId:p.id,revision:p.revision,action:'remove',entryId:entry.id});const updated=(await s.detail(actor,'client',id,{})).period;const candidates=(await s.candidates(actor,'client',id,p.id,{})).items;await s.mutate(actor,'client',id,{key:require('node:crypto').randomUUID(),periodId:p.id,revision:updated.revision,action:'allocate',entries:candidates.map(t=>({id:t.id,version:t.version}))});assert.equal((await pool.query("select count(*)::int n from workflow_events where trigger='retainer_80'")).rows[0].n,1);
  await assert.rejects(activeRule({trigger:'retainer_80',actionType:'create_task'}),{code:'INVALID_RULE'});
 });
 test('overage action reuses the closed statement draft without duplicating monthly billing',async()=>{
  const rid=await activeRule({trigger:'retainer_overage_approved',actionType:'prepare_billing'});const{s,id,p}=await consumedRetainer();await s.mutate(actor,'client',id,{key:require('node:crypto').randomUUID(),periodId:p.id,revision:p.revision,action:'close',confirm:true});const closed=(await s.detail(actor,'client',id,{periodId:p.id})).period;
  await s.mutate({id:'other',role:'client',organizationId:'org-a'},'client',id,{key:require('node:crypto').randomUUID(),periodId:p.id,revision:closed.revision,action:'decide',decision:'approved',note:'Approved',confirm:true});await Promise.all([run(),run()]);const h=(await service.inspect(actor,rid,false))[0];assert.equal(h.outcome,'billing_prepared');assert.equal(h.resourceId,closed.statement.billing.id);assert.equal(h.details.amount,'10.00');assert.equal(await count('invoices'),0);
 });
 test('external channels require opt-in and queue once; disabling a preference before delivery sends nothing',async()=>{
  const rid=await activeRule({channel:'email'});await event();await run();let h=(await service.inspect(actor,rid,false))[0];assert.equal(h.outcome,'preferences_disabled');assert.equal(await count('durable_jobs'),0);await pool.query(`update users set notification_preferences='{"emailNotifications":true,"projectActivityUpdates":true}' where id='owner'`);await service.retry(actor,rid,h.id);assert.equal(await count('durable_jobs'),1);h=(await service.inspect(actor,rid,false))[0];assert.equal(h.outcome,'queued');
  await pool.query(`update users set notification_preferences='{"emailNotifications":false}' where id='owner'`);let sends=0;const c=await pool.connect();try{await require('../src/modules/workflows/delivery').deliverWorkflow(c,h.id,async()=>{sends++;return true})}finally{c.release()}assert.equal(sends,0);h=(await service.inspect(actor,rid,false))[0];assert.equal(h.outcome,'preferences_disabled');assert.equal(h.canRetry,false);
 });
 test('provider failure remains uncertain, never claims sent and cannot be blindly retried',async()=>{
  await pool.query(`update users set notification_preferences='{"emailNotifications":true}' where id='owner'`);const rid=await activeRule({channel:'email'});await event();await run();const h=(await service.inspect(actor,rid,false))[0];let sends=0;const queue=require('../src/services/jobs/queue'),handler={'workflow-delivery':{transactional:false,retryable:false,run:(job,c)=>require('../src/modules/workflows/delivery').deliverWorkflow(c,String(job.payload.executionId),async()=>{sends++;return false})}};await queue.runOne(pool,handler,e=>{throw e});assert.equal(await queue.runOne(pool,handler,e=>{throw e}),false);assert.equal(sends,1);const after=(await service.inspect(actor,rid,false))[0];assert.equal(after.outcome,'uncertain');assert.equal(after.canRetry,false);await assert.rejects(service.retry(actor,rid,h.id),{code:'RETRY_UNSAFE'});
 });
 test('paused rule cancels queued delivery and history never announces a successful send',async()=>{
  await pool.query(`update users set notification_preferences='{"emailNotifications":true}' where id='owner'`);const rid=await activeRule({channel:'email'});await event();await run();const h=(await service.inspect(actor,rid,false))[0];await service.setEnabled(actor,rid,{enabled:false});let sends=0;const c=await pool.connect();try{await require('../src/modules/workflows/delivery').deliverWorkflow(c,h.id,async()=>{sends++;return true})}finally{c.release()}assert.equal(sends,0);assert.equal((await service.inspect(actor,rid,false))[0].outcome,'delivery_cancelled');
 });


 test('approved delivery whose milestone changes cannot create a task from stale approval',async()=>{
  await clientFixture();const rid=await activeRule({actionType:'create_task'});await pool.query("insert into project_milestones(id,project_id,organization_id,title,status,created_at,updated_at) values('milestone','project','org-a','Design','pending',now(),now())");
  const module=require('../src/modules/delivery/service'),delivery=module.createDeliveryReviews(pool),milestone=(await pool.query("select * from project_milestones where id='milestone'")).rows[0],version=module.milestoneVersion(milestone);
  const review=await delivery.request(actor,'project',{milestoneId:'milestone',version,note:'Please review'});await delivery.decide({id:'other',role:'client',organizationId:'org-a'},'project',review.id,{version,state:'approved',comment:''});await pool.query("update project_milestones set title='Changed design',updated_at=clock_timestamp() where id='milestone'");await run();assert.equal((await service.inspect(actor,rid,false))[0].outcome,'source_changed');assert.equal(await count('tasks'),0);
 });
 test('queue reports provider acceptance only after the delivery job completes',async()=>{
  await pool.query(`update users set notification_preferences='{"emailNotifications":true}' where id='owner'`);const rid=await activeRule({channel:'email'});await event();await run();assert.equal((await service.inspect(actor,rid,false))[0].outcome,'queued');let sends=0;
  await require('../src/services/jobs/queue').runOne(pool,{'workflow-delivery':{transactional:false,retryable:false,run:(job,c)=>require('../src/modules/workflows/delivery').deliverWorkflow(c,String(job.payload.executionId),async()=>{sends++;return true})}},e=>{throw e});assert.equal(sends,1);assert.equal((await service.inspect(actor,rid,false))[0].outcome,'sent');
 });
}
