const {test,before,beforeEach,after}=require('node:test');const assert=require('node:assert/strict');
if(!process.env.WORKFLOWS_TEST_DATABASE_URL)test('Workflows PostgreSQL',{skip:true},()=>{});
else{
 const url=new URL(process.env.WORKFLOWS_TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55442'&&url.pathname==='/flowlio_workflows_test');
 const {Pool}=require('pg'),pool=new Pool({connectionString:url.toString()});const {createWorkflows,processWorkflowOrganization}=require('../src/modules/workflows/service'),service=createWorkflows(pool);
 const actor={id:'owner',role:'user',organizationId:'org-a',isOrganizationOwner:true};
 const draft={name:'Accepted delivery',trigger:'delivery_approved',projectStatus:null,title:'Delivery accepted',message:'Review the next project milestone.'};
 before(async()=>{await pool.query('drop schema public cascade;create schema public;drop schema if exists flowlio_releases cascade;drop schema if exists drizzle cascade');await require('../src/utils/release-migrations.util').runReleaseMigrations(pool)});
 beforeEach(async()=>{await pool.query(`truncate users,organizations cascade;
 insert into users(id,name,email,role,status,is_organization_owner,email_verified,two_factor_enabled,is_super_admin,timezone,created_at,updated_at) values('owner','Owner','owner@example.test','user','active',true,true,false,false,'UTC',now(),now()),('other','Other','other@example.test','user','active',true,true,false,false,'UTC',now(),now());
 insert into organizations(id,name,slug,status,subscription_status,created_at,updated_at) values('org-a','A','a','active','active',now(),now()),('org-b','B','b','active','active',now(),now());
 insert into user_organizations(id,user_id,organization_id,role,status,created_at,updated_at) values('m1','owner','org-a','owner','active',now(),now());
 insert into projects(id,name,project_number,organization_id,created_by,visibility,status,created_at,updated_at) values('project','Project','1','org-a','owner','private','pending',now(),now());`);});
 after(()=>pool.end());
 async function rule(){const r=await service.create(actor,draft);await service.setEnabled(actor,r.id,{enabled:true});return r.id;}
 async function event(id='event'){await pool.query("insert into recent_activities(id,organization_id,actor_id,type,action,resource,resource_id,created_at) values($1,'org-a','owner','delivery','delivery_approved','project','project',clock_timestamp())",[id]);}
 async function run(){const client=await pool.connect();try{await client.query('begin');await processWorkflowOrganization(client,'org-a');await client.query('commit')}catch(e){await client.query('rollback');throw e}finally{client.release()}}
 test('simulation reads persisted events without notifications or execution writes',async()=>{const id=await rule();await event();assert.deepEqual(await service.inspect(actor,id,true),{sampled:1,matches:1,limit:100});assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);assert.equal((await service.inspect(actor,id,false)).length,0);});
 test('concurrent retries notify once and do not generate chained activity',async()=>{const id=await rule();await event();await Promise.all(Array.from({length:8},run));assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,1);assert.equal((await service.inspect(actor,id,false)).length,1);assert.equal((await pool.query('select count(*)::int n from recent_activities')).rows[0].n,1);});
 test('condition mismatch is recorded without notification',async()=>{const r=await service.create(actor,{...draft,projectStatus:'completed'});await service.setEnabled(actor,r.id,{enabled:true});await event();await run();assert.equal((await service.inspect(actor,r.id,false))[0].outcome,'condition_not_met');assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);});
 test('private projects, foreign organizations and other rule authors remain isolated',async()=>{const id=await rule();await event();await pool.query("update projects set created_by='other'");await run();assert.equal((await service.inspect(actor,id,false))[0].outcome,'inaccessible');assert.equal((await service.inspect(actor,id,true)).sampled,0);await assert.rejects(service.inspect({...actor,organizationId:'org-b'},id,false),{code:'RULE_NOT_FOUND'});await assert.rejects(service.setEnabled({...actor,id:'other'},id,{enabled:false}),{code:'RULE_NOT_FOUND'});});
 test('revoked membership pauses rule before any effect',async()=>{const id=await rule();await event();await pool.query("update user_organizations set status='inactive'");await run();assert.equal((await service.list(actor))[0].enabled,false);assert.equal((await service.inspect(actor,id,false)).length,0);assert.equal((await pool.query('select count(*)::int n from notifications')).rows[0].n,0);});
 test('paused and pre-activation events are not replayed when enabling',async()=>{const id=await rule();await service.setEnabled(actor,id,{enabled:false});await event();await run();await service.setEnabled(actor,id,{enabled:true});await run();assert.equal((await service.inspect(actor,id,false)).length,0);await event('new');await run();assert.equal((await service.inspect(actor,id,false)).length,1);});
 test('failed notification rolls back execution marker and retry succeeds once',async()=>{const id=await rule();await event();await pool.query("create function fail_workflow_notification() returns trigger language plpgsql as $$ begin raise exception 'test';end $$;create trigger fail_workflow before insert on notifications for each row execute function fail_workflow_notification()");try{await assert.rejects(run());assert.equal((await service.inspect(actor,id,false)).length,0)}finally{await pool.query('drop trigger fail_workflow on notifications;drop function fail_workflow_notification()')}await run();assert.equal((await service.inspect(actor,id,false)).length,1);});
 test('members cannot configure rules and rule payload cannot choose another recipient',async()=>{await assert.rejects(service.create({...actor,isOrganizationOwner:false},draft),{code:'FORBIDDEN'});await assert.rejects(service.create(actor,{...draft,userId:'other'}),{code:'INVALID_RULE'});});
}
